### PR TITLE
UPDATED: Exit Games Photon SDK information

### PR DESCRIPTION
**Pull request by exitgames**
Updated the product, company and SDKs information, please pull ...

### CODE REVIEW

**Comment by gurdotan** [comment]
@exitgames thanks for your PR.  Could you please reduce the number of tags to say 4-6? This is so that it would be fairly weighted for all other SDKs.  Thanks

**Comment by exitgames** [comment]
np, sure ... done :]

**Comment by gurdotan** [comment]
Deployed, please allow several minutes for Github pages to invalidate cache.

On another note, we've just set up code samples of SDKs like yours and how they work with SOOMLA. See http://know.soom.la/integrations/

Vendors are free to contribute use cases and code samples, if you'd like more info email me - gur@soom.la

Cheers

**Comment by exitgames** [comment]
Thanks for the extra info and the fast merge!

Cheers

**Pull request merged**
