### PR TITLE
Update Batch.com metadatas

### PR DESCRIPTION
**Pull request by guenard**

### CODE REVIEW

**Comment by gurdotan** [comment]
Thanks for the PR.  However, we don't have an icon for Cordova in there.  You can add it by adding an entry called `cordova` into the `platforms` object here:
https://github.com/guenard/gamegear.io/blob/master/client/app/sdks.js#L4

The image needs to follow these requirements:

* Needs to be a data URL (use http://dataurl.net/#dataurlmaker if you need)
* Transparent background
* Dimensions of 20x20 (the width can be +- a few pixels, but it needs to be tightly cropped and the height has to be 20 pixels)
* Tightly cropped - no more than 1-2 empty pixels on the sides, top and bottom.
* The logo's body color should be `#979797`

If you can get all those requirements into this PR, then I'm happy to accept it.  Thanks!

**Comment by gurdotan** [comment]
@guenard any updates on this?

**Comment by guenard** [comment]
@gurdotan i just replaced Cordova with Phonegap as it's the exact same technology. All Phonegap plugins are compatible with Ionic Framework and Cordova.

**Comment by guenard** [comment]
@gurdotan is that ok for you?

**Comment by gurdotan** [comment]
Deployed

**Pull request merged**
